

export const ADD_PLAN = 'ADD_PLAN';
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const ADD_PLANS = 'ADD_PLANS';
export const PLANS_LOADING = 'PLANS_LOADING';
export const PLANS_FAILED = 'PLANS_FAILED';

export const ADD_FUNCS = 'ADD_FUNCS';
export const FUNCS_LOADING = 'FUNCS_LOADING';
export const FUNCS_FAILED = 'FUNCS_FAILED';




export const ADD_EMPRESA = 'ADD_EMPRESA';
export const ADD_EMPRESAS = 'ADD_EMPRESAS';
export const EMPRESAS_LOADING = 'EMPRESAS_LOADING';
export const EMPRESAS_FAILED = 'EMPRESAS_FAILED';

export const ADD_USUARIO = 'ADD_USUARIO';
export const ADD_USUARIOS = 'ADD_USUARIOS';
export const USUARIOS_LOADING = 'USUARIOS_LOADING';
export const USUARIOS_FAILED = 'USUARIOS_FAILED';
export const UPDATE_USUARIO = 'UPDATE_USUARIO';

export const ADD_EMPLEADO = 'ADD_EMPLEADO';
export const ADD_EMPLEADOS = 'ADD_EMPLEADOS';
export const EMPLEADOS_LOADING = 'EMPLEADOS_LOADING';
export const EMPLEADOS_FAILED = 'EMPLEADOS_FAILED';
export const UPDATE_EMPLEADO = 'UPDATE_EMPLEADO';

export const ADD_CLIENTE = 'ADD_CLIENTE';
export const ADD_CLIENTES = 'ADD_CLIENTES';
export const CLIENTES_LOADING = 'CLIENTES_LOADING';
export const CLIENTES_FAILED = 'CLIENTES_FAILED';
export const UPDATE_CLIENTE = 'UPDATE_CLIENTE';