export const ADD_PLANS = 'ADD_PLAN';
export const PLANS_LOADING = 'PLANS_LOADING';
export const PLANS_FAILED = 'PLANS_FAILED';
export const ADD_FUNCS = 'ADD_FUNCS';
export const FUNCS_LOADING = 'FUNCS_LOADING';
export const FUNCS_FAILED = 'FUNCS_FAILED';

export const ADD_EMPRESA = 'ADD_EMPRESA';
export const ADD_EMPRESAS = 'ADD_EMPRESAS';
export const EMPRESAS_LOADING = 'EMPRESAS_LOADING';
export const EMPRESAS_FAILED = 'EMPRESAS_FAILED';