
//PLANES ROUKKA
export const ADD_PLAN = 'ADD_PLAN';
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const ADD_PLANS = 'ADD_PLANS';
export const PLANS_LOADING = 'PLANS_LOADING';
export const PLANS_FAILED = 'PLANS_FAILED';

//FUNCIONALIDADES ROUKKA
export const ADD_FUNCIONALIDAD = 'ADD_FUNCIONALIDAD';
export const UPDATE_FUNCIONALIDAD = 'UPDATE_FUNCIONALIDAD';
export const ADD_FUNCIONALIDADES = 'ADD_FUNCIONALIDADES';
export const FUNCIONALIDADES_LOADING = 'FUNCIONALIDADES_LOADING';
export const FUNCIONALIDADES_FAILED = 'FUNCIONALIDADES_FAILED';

//EMPRESAS ROUKKA
export const ADD_EMPRESA = 'ADD_EMPRESA';
export const ADD_EMPRESAS = 'ADD_EMPRESAS';
export const EMPRESAS_LOADING = 'EMPRESAS_LOADING';
export const EMPRESAS_FAILED = 'EMPRESAS_FAILED';

//USUARIOS ROUKKA
export const ADD_USUARIO = 'ADD_USUARIO';
export const ADD_USUARIOS = 'ADD_USUARIOS';
export const USUARIOS_LOADING = 'USUARIOS_LOADING';
export const USUARIOS_FAILED = 'USUARIOS_FAILED';
export const UPDATE_USUARIO = 'UPDATE_USUARIO';

//USUARIOS TENANT
export const ADD_USUARIOT = 'ADD_USUARIOT';
export const ADD_USUARIOST = 'ADD_USUARIOST';
export const USUARIOST_LOADING = 'USUARIOST_LOADING';
export const USUARIOST_FAILED = 'USUARIOST_FAILED';
export const UPDATE_USUARIOT = 'UPDATE_USUARIOT';

//EMPLEADOS TENANT
export const ADD_EMPLEADO = 'ADD_EMPLEADO';
export const ADD_EMPLEADOS = 'ADD_EMPLEADOS';
export const EMPLEADOS_LOADING = 'EMPLEADOS_LOADING';
export const EMPLEADOS_FAILED = 'EMPLEADOS_FAILED';
export const UPDATE_EMPLEADO = 'UPDATE_EMPLEADO';

//CLIENTES TENANT
export const ADD_CLIENTE = 'ADD_CLIENTE';
export const ADD_CLIENTES = 'ADD_CLIENTES';
export const CLIENTES_LOADING = 'CLIENTES_LOADING';
export const CLIENTES_FAILED = 'CLIENTES_FAILED';
export const UPDATE_CLIENTE = 'UPDATE_CLIENTE';

//INFORMACION TENANT
export const ADD_INFORMACION = 'ADD_INFORMACION'
export const ADD_DATOS = 'ADD_DATOS'
export const UPDATE_INFORMACION = 'UPDATE_INFORMACION'
export const INFORMACION_LOADING = 'INFORMACION_LOADING'
export const INFORMACION_FAILED = 'INFORMACION_FAILED'
export const DELETE_INFORMACION = 'DELETE_INFORMACION'

//INGREDIENTES TENANT
export const ADD_INGREDIENTE = 'ADD_INGREDIENTE'
export const ADD_INGREDIENTES = 'ADD_INGREDIENTES'
export const UPDATE_INGREDIENTE = 'UPDATE_INGREDIENTE'
export const INGREDIENTE_LOADING = 'INGREDIENTE_LOADING'
export const INGREDIENTE_FAILED = 'INGREDIENTE_FAILED'
export const DELETE_INGREDIENTE = 'DELETE_INGREDIENTE'

//TEMA TENANT
export const UPDATE_TEMA = 'UPDATE_TEMA'
export const ADD_TEMA = 'ADD_TEMA'

export const ADD_PLATILLO = 'ADD_PLATILLO'
export const ADD_PLATILLOS = 'ADD_PLATILLOS'
export const UPDATE_PLATILLO = 'UPDATE_PLATILLO'
export const PLATILLO_LOADING = 'PLATILLO_LOADING'
export const PLATILLO_FAILED = 'PLATILLO_FAILED'


export const ADD_MENU = 'ADD_MENU'
export const ADD_MENUS = 'ADD_MENUS'
export const UPDATE_MENU = 'UPDATE_MENU'
export const MENU_LOADING = 'MENU_LOADING'
export const MENU_FAILED = 'MENU_FAILED'

export const ADD_CARRITO = 'ADD_CARRITO'

export const GET_ERRORS = 'GET_ERRORS'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'

//Types de Login
//export const USER_LOADING = 'USER_LOADING'
//export const USER_LOADED = 'USER_LOADED'
//export const AUTH_ERROR = 'AUTH_ERROR'


//export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
//export const LOGIN_FAIL = 'LOGIN_FAIL'

//export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//FACTURA

export const ADD_ITEM = 'ADD_ITEM'
export const PLUS_ITEM = 'PLUS_ITEM'
export const LESS_ITEM = 'LESS_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const MODAL_FACTURA = 'MODAL_FACTURA'

export const DONE_FACTURA = 'DONE_FACTURA'

